---
title: "gapminder report"
author: "A. Ginolhac"
date: "2020-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(targets)
library(tidyverse)
```

## Gapminder Data


we used:

- the URL `r tar_read(gp_url)`
- to download the file `r tar_read(gp_file)`

Tibble is then:

```{r}
tar_load(gp)
gp
```

## Grouping

`tar_group()` will create a new column to match the `dplyr` grouping we did

```{r}
tar_read(gp_grp)
```

## Combine results

```{r paged.print=FALSE}
tar_read(gp_grp) %>% 
  group_by(continent, country, tar_group) %>% 
  tidyr::nest() %>% 
  ungroup() %>%
  inner_join(tibble(rsq = tar_read(r2),
                    tar_group = seq_len(length(tar_read(r2))))) -> gp_r2
gp_r2
```


## Snake plot

```{r}
gp_r2 %>% 
  ggplot(aes(x = rsq, y = forcats::fct_reorder(country, rsq))) +
  geom_point(aes(colour = continent)) +
  labs(y = NULL,
       x = "r squared") +
  theme_classic(18) +
  theme(legend.position = c(0.2, 0.7),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
```


### highlight African countries

```{r}
gp_r2 %>% 
  unnest(data) %>% 
  ggplot(aes(x = year, y = lifeExp, group = country)) +
  geom_line() +
  gghighlight::gghighlight(rsq < 0.1, use_direct_label = TRUE,
                           label_params = list(hjust = 1, vjust = 1, 
                                               fill = "red", colour = "white", 
                                               alpha = 0.7)) +
  theme_minimal(14) +
  labs(title = "Gapminder",
       subtitle = "rsq of lifeExp ~ year < 0.1")
```

