#! /bin/bash
################################################################################
# stressme - A sample workload generator that imposes a configurable amount of
#            stress on the system using the 'stress' command
# Time-stamp: <Thu 2020-12-10 15:14 svarrette>
################################################################################
# Local variables
CMD_PREFIX=
STRESS=$(which stress)
OPTIONS="-c 1"
# Default timeout (in seconds)
TIMEOUT=20

############################################################
print_error_and_exit() { echo "*** ERROR ***: $*"; exit 1; }
usage() {
    cat <<EOF
NAME
  $(basename $0): A sample workload generator that imposes a stress on the
     computing node using the 'stress' command.
USAGE
  $0 [-n] [N]:  run serial stress during N second (Default: ${TIMEOUT})
OPTIONS
  -n --noop --dry-run:     Dry run mode
EOF
}

################################################################################
# Check for options
while [ $# -ge 1 ]; do
    case $1 in
        -h | --help) usage; exit 0;;
        -n | --noop | --dry-run) CMD_PREFIX=echo;;
        *) TIMEOUT="$*"; break;;
    esac
    shift
done
[ -z "${STRESS}" ] && print_error_and_exit "Unable to find the 'stress' command"
CMD="${CMD_PREFIX} ${STRESS} ${OPTIONS} -t ${TIMEOUT}"
echo "# ${CMD}"

${CMD}
