# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.synced_folder "output/", "/vagrant/output"

  config.vm.provision "shell", inline: <<-SHELL
    yum update
    yum install -y gnuplot
    curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    python get-pip.py
    pip install virtualenv
    cd /vagrant
    virtualenv env
    source env/bin/activate
    pip install filelock
    make test
    deactivate
  SHELL
end
